// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto1.Data;

#nullable disable

namespace Proyecto1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250804035119_AgregaLavados")]
    partial class AgregaLavados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto1.Models.Cliente", b =>
                {
                    b.Property<int>("Identificacion")
                        .HasColumnType("int");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionExacta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreferenciaLavado")
                        .HasColumnType("int");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Identificacion");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Proyecto1.Models.Empleado", b =>
                {
                    b.Property<int>("Cedula")
                        .HasColumnType("int");

                    b.Property<int>("DiasVacacionesAcumulados")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRetiro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoLiquidacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalarioPorDia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Cedula");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Proyecto1.Models.Lavado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteIdentificacion")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("VehiculoPlaca")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("nombreTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("precio_con_iva")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteIdentificacion");

                    b.HasIndex("VehiculoPlaca");

                    b.ToTable("Lavados");
                });

            modelBuilder.Entity("Proyecto1.Models.TipoLavado", b =>
                {
                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.PrimitiveCollection<string>("prestaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("TipoLavado");
                });

            modelBuilder.Entity("Vehiculo", b =>
                {
                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Traccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TratamientoEspecialNano")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UltimaFechaAtencion")
                        .HasColumnType("datetime2");

                    b.HasKey("Placa");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Proyecto1.Models.Lavado", b =>
                {
                    b.HasOne("Proyecto1.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteIdentificacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoPlaca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Vehiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
